// Generated by FastCC v.8.0 - Do not edit this line!

package it.smartio.fastcc.jjtree;

public class ASTBNFDeclaration extends JJTreeNode {

  public ASTBNFDeclaration(JJTreeParser p, int id) {
    super(p, id);
  }

  public NodeScope node_scope;

  /** Accept the visitor. **/
  @Override
  public final Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
// FastCC Checksum=B96B197307C037C9BB7885553247912A (Do not edit this line!)
// FastCC Options: NODE_FACTORY='', VISITOR_DATA_TYPE='', VISITOR='true', NODE_CLASS='JJTreeNode', NODE_TYPE='ASTBNFDeclaration', VISITOR_RETURN_TYPE_VOID='false', VISITOR_EXCEPTION='', PARSER_NAME='JJTreeParser', VISITOR_RETURN_TYPE='Object'
