// Generated by FastCC v.8.0 - Do not edit this line!

package it.smartio.fastcc.jjtree;

public class ASTExpansionNodeScope extends JJTreeNode {

  public ASTExpansionNodeScope(JJTreeParser p, int id) {
    super(p, id);
  }

  public NodeScope  node_scope;
  public JJTreeNode expansion_unit;

  @Override
  public final Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
// FastCC Checksum=7B7A74451CC55AAAB18206D85AEFC14B (Do not edit this line!)
// FastCC Options: NODE_FACTORY='', VISITOR_DATA_TYPE='', VISITOR='true', NODE_CLASS='JJTreeNode', NODE_TYPE='ASTExpansionNodeScope', VISITOR_RETURN_TYPE_VOID='false', VISITOR_EXCEPTION='', PARSER_NAME='JJTreeParser', VISITOR_RETURN_TYPE='Object'
