// Generated by FastCC v.8.0 - Do not edit this line!

package it.smartio.fastcc.jjtree;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;

public class ASTNodeDescriptor extends JJTreeNode {

  ASTNodeDescriptor(int id) {
    super(id);
  }

  private boolean faked = false;

  static ASTNodeDescriptor indefinite(String s) {
    ASTNodeDescriptor nd = new ASTNodeDescriptor(JJTreeParserTreeConstants.JJTNODEDESCRIPTOR);
    nd.name = s;
    nd.setNodeIdValue();
    nd.faked = true;
    return nd;
  }


  private static List<String>              nodeIds   = new ArrayList<>();
  private static List<String>              nodeNames = new ArrayList<>();
  private static Hashtable<String, String> nodeSeen  = new Hashtable<>();

  public static List<String> getNodeIds() {
    return ASTNodeDescriptor.nodeIds;
  }

  public static List<String> getNodeNames() {
    return ASTNodeDescriptor.nodeNames;
  }

  void setNodeIdValue() {
    String k = getNodeId();
    if (!ASTNodeDescriptor.nodeSeen.containsKey(k)) {
      ASTNodeDescriptor.nodeSeen.put(k, k);
      ASTNodeDescriptor.nodeNames.add(this.name);
      ASTNodeDescriptor.nodeIds.add(k);
    }
  }

  public String getNodeId() {
    return "JJT" + this.name.toUpperCase().replace('.', '_');
  }


  String                      name;
  boolean                     isGT;
  private String                      text;


  boolean isVoid() {
    return this.name.equals("void");
  }

  @Override
  public String toString() {
    if (this.faked) {
      return "(faked) " + this.name;
    } else {
      return super.toString() + ": " + this.name;
    }
  }
  
  public void setExpressionText(String text) {
    this.text = text;
  }

  public String getDescriptor() {
    if (this.text == null) {
      return this.name;
    } else {
      return "#" + this.name + "(" + (this.isGT ? ">" : "") + this.text + ")";
    }
  }

  public String getNodeType() {
    return JJTreeOptions.getMulti() ? JJTreeOptions.getNodePrefix() + this.name : "Node";
  }


  public String openNode(String nodeVar) {
    return "jjtree.openNodeScope(" + nodeVar + ");";
  }


  public String closeNode(String nodeVar) {
    if (this.text == null) {
      return "jjtree.closeNodeScope(" + nodeVar + ", true);";
    } else if (this.isGT) {
      return "jjtree.closeNodeScope(" + nodeVar + ", jjtree.nodeArity() >" + this.text + ");";
    } else {
      return "jjtree.closeNodeScope(" + nodeVar + ", " + this.text + ");";
    }
  }

  @Override
  public String translateImage(Token t) {
    return whiteOut(t);
  }

  @Override
  public final Object jjtAccept(JJTreeParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}